export const PRIVE_CATEGORIEEN = [
  "Boodschappen",
  "Cash opname",
  "Aanvulling Creditcard",
  "Uit eten / café",
  "Take away",
  "Transport",
  "Wonen & utilities",
  "Verzekering",
  "Abonnementen",
  "Bank kosten",
  "Gezondheid",
  "Gezamenlijke rekening",
  "Hypotheek",
  "Kleding",
  "Lening",
  "Opleiding",
  "Vrije tijd",
  "Vakantie",
  "Overig",
];
